#!/usr/bin/env python3
"""Generate committed PDF fixtures + validation manifest for app/domain/tests/pdf_export.rs.

Run from anywhere; writes into tests/fixtures/pdf/ next to this script.

    python3 generate.py

Pipeline:
  1. Fixture bytes are produced by the crate's own writer through the
     `gen_pdf_fixture` example (`cargo run --example gen_pdf_fixture`), so
     every committed fixture is byte-for-byte what the shipped code emits.
     Byte-exactness is additionally pinned by the crate's golden digest
     tests.
  2. This script then cross-parses each committed fixture with PyMuPDF —
     an independent PDF implementation — asserting, per fixture:
       * exact page count,
       * exact per-page MediaBox pixel dimensions (1 pt = 1 px convention),
       * the single image XObject on each page decodes to the expected
         pixel bytes whose SHA-256 matches the crate's GrayFrame digest
         recipe ('foldscan.frame/1' || w_le32 || h_le32 || pixels).

Requires: pymupdf.  (Development-time tool; CI for app/domain does not run
this script — it consumes the committed fixtures and manifest.)
"""

import hashlib
import json
import struct
import subprocess
from pathlib import Path

import pymupdf

HERE = Path(__file__).parent

# Same frozen LCG as golden_processing.rs, pdf.rs tests, and the PNG fixtures.
def lcg_bytes(w: int, h: int, seed: int) -> bytes:
    s = seed & 0xFFFF
    out = bytearray()
    for _ in range(w * h):
        s = ((s * 25173 + 13849) << 3 & 0xFFFF) ^ (s >> 5)
        out.append((s >> 8) & 0xFF)
    return bytes(out)


def gray_digest(w: int, h: int, pixels: bytes) -> str:
    hsh = hashlib.sha256(b"foldscan.frame/1" + struct.pack("<II", w, h) + pixels)
    return hsh.hexdigest()


# (file, pages as [(w, h, seed), ...]) — mirrors the fixture spec below.
FIXTURES = [
    ("one_page_5x4.pdf", [(5, 4, 11)]),
    ("three_pages.pdf", [(16, 12, 1), (11, 7, 2), (40, 1, 3)]),
]


def render_with_writer(specs):
    """Generate PDF bytes via a throwaway Rust test binary in a scratch dir.

    Runs `cargo test --locked --lib` with an env-gated capture? No — keeps
    it simpler: we ask cargo to compile a tiny example-like integration
    test that writes the fixture to stdout via the test harness. To avoid
    any production test-side effects, generation instead re-implements the
    byte-exact layout independently *only as a cross-check* and commits the
    bytes captured from the actual Rust writer by running the crate's
    example target:

        cargo run --example gen_pdf_fixture -- <w> <h> <seed> [...]
    """
    raise RuntimeError("see main(); generation goes through the example binary")


def capture(fixture_path: Path, frames):
    """Invoke the crate's example binary to write this fixture's bytes."""
    args = [
        "cargo", "run", "--quiet", "--locked", "--example", "gen_pdf_fixture", "--",
        str(fixture_path),
    ]
    for (w, h, seed) in frames:
        args += [str(w), str(h), str(seed)]
    root = HERE.parent.parent.parent  # app/domain
    subprocess.run(args, check=True, cwd=root)


def validate(path: Path, frames):
    """Independent-parse the committed fixture with PyMuPDF."""
    doc = pymupdf.open(str(path))
    assert len(doc) == len(frames), f"{path}: {len(doc)} pages, expected {len(frames)}"
    per_page = []
    for i, (w, h, seed) in enumerate(frames):
        page = doc[i]
        rect = page.rect
        assert int(rect.width) == w and int(rect.height) == h, (
            f"{path} page {i}: MediaBox {rect.width}x{rect.height}, expected {w}x{h}"
        )
        imgs = page.get_images(full=True)
        assert len(imgs) == 1, f"{path} page {i}: {len(imgs)} images, expected 1"
        xref = imgs[0][0]
        pix = pymupdf.Pixmap(doc, xref)
        assert pix.width == w and pix.height == h, f"{path} page {i}: image size mismatch"
        assert pix.n == 1, f"{path} page {i}: {pix.n} samples/px, expected 1 (gray)"
        got = pix.samples
        want = lcg_bytes(w, h, seed)
        assert got == want, f"{path} page {i}: decoded pixels differ from source frame"
        per_page.append({"w": w, "h": h, "seed": seed, "digest": gray_digest(w, h, want)})
    doc.close()
    return per_page


def main():
    manifest = {
        "_comment": (
            "Generated by generate.py; byte-exactness pinned by pdf.rs golden digests, "
            "structure/pixels independently cross-parsed with PyMuPDF at generation time. "
            "digest = SHA-256('foldscan.frame/1'||w_le32||h_le32||pixels) = GrayFrame::digest()."
        ),
        "tool": f"pymupdf {pymupdf.__version__}",
        "fixtures": [],
    }
    for name, frames in FIXTURES:
        path = HERE / name
        capture(path, frames)
        per_page = validate(path, frames)
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        manifest["fixtures"].append({"file": name, "sha256": digest, "pages": per_page})
        print(f"OK {name}: {len(frames)} page(s), sha256={digest[:16]}…")
    (HERE / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print("wrote manifest.json")


if __name__ == "__main__":
    main()
