//! Golden-fixture gate for the deterministic processing core (issue #5).
//!
//! These tests lock the *exact* digests of processed output for a set of
//! synthetic golden inputs (rotation, skew, shadow, noise, corruption)
//! against committed expected values. Any change to a primitive's rounding,
//! pooling, or mapping math that alters output bytes on any IEEE-754 host
//! will fail here, which is the reviewable signal that a recipe's stored
//! digests are about to go stale for real users.
//!
//! The frames are generated by an LCG, not `rand`, so the golden inputs
//! themselves are reproducible from this file alone; no personal document
//! content is involved.
//!
//! Evidence category: software golden-digest fixtures on synthetic frames.
//! No image codecs, no physical device, no optical bench.

use foldscan_domain::image::GrayFrame;
use foldscan_domain::{
    apply_recipe, DeterministicProcessor, OpKind, ProcessingRecipe, Processor, RecipeOp,
};
use serde_json::json;

/// Deterministic input generator: 16-bit LCG (parameters chosen ad hoc and
/// frozen; changing them invalidates every golden digest below).
struct Lcg(u16);

impl Lcg {
    fn next(&mut self) -> u8 {
        self.0 = self
            .0
            .wrapping_mul(25173)
            .wrapping_add(13849)
            .wrapping_shl(3)
            ^ self.0.wrapping_shr(5);
        (self.0 >> 8) as u8
    }
}

fn noisy_frame(w: u32, h: u32, seed: u16) -> GrayFrame {
    let mut rng = Lcg(seed);
    let pixels = (0..(w * h)).map(|_| rng.next()).collect();
    GrayFrame::from_pixels(w, h, pixels).expect("golden input")
}

/// A synthetic "photo with a shadow gradient": flat page tone plus a
/// monotone darkening toward the bottom-left, generated by pure integer ops.
fn shadow_frame(w: u32, h: u32) -> GrayFrame {
    let mut pixels = Vec::with_capacity((w * h) as usize);
    for y in 0..h {
        for x in 0..w {
            let base: i32 = 200;
            // Distance from top-right corner drives the shadow depth.
            let dx = (w - x) as i32;
            let dy = y as i32;
            let depth = (dx + dy) / (((w + h) / 4).max(1) as i32);
            let v = (base - depth * 18).clamp(30, 255) as u8;
            pixels.push(v);
        }
    }
    GrayFrame::from_pixels(w, h, pixels).expect("shadow frame")
}

fn recipe_of(ops: Vec<(&str, serde_json::Value)>) -> ProcessingRecipe {
    ProcessingRecipe {
        schema: "foldscan.recipe/0.1".to_string(),
        name: "golden".to_string(),
        ops: ops
            .into_iter()
            .map(|(k, v)| RecipeOp {
                kind: match k {
                    "rotate" => OpKind::Rotate,
                    "crop" => OpKind::Crop,
                    "perspective" => OpKind::Perspective,
                    "illumination" => OpKind::Illumination,
                    _ => OpKind::Dewarp,
                },
                params: v,
            })
            .collect(),
    }
}

fn golden(name: &str, input: &GrayFrame, ops: Vec<(&str, serde_json::Value)>) -> String {
    let r = recipe_of(ops);
    let p = DeterministicProcessor;
    let out = p
        .process(input, &r)
        .unwrap_or_else(|e| panic!("{name}: {e}"));
    assert_eq!(out.digest, out.frame.digest(), "{name}: digest binding");
    out.digest
}

// Golden digests were generated by this exact code on x86-64 (IEEE-754)
// and are asserted stable on every CI host (ubuntu-latest, same contract).

const GOLDEN_ROTATE90_CROP: &str =
    "4d5bde35b972de737c977a7b655761381f29dcc6662b71180157179864da3342";
const GOLDEN_SKEW_RECTIFY: &str =
    "d97082401f2c84f19239893758558e7cfb361e1dcc96b6576465b2453e9057e6";
const GOLDEN_SHADOW_FLATTEN: &str =
    "16a5e5c720be07ebfe098fa6fef7a3665bf52f405459b9417b54245e97d1147f";
const GOLDEN_CHAINED_PIPELINE: &str =
    "1879cea85f1607eacb3f7f4056fada1352ec8c2b2099f702f3b932badee28a56";
const GOLDEN_BALANCE_ON_SHADOW: &str =
    "43cd28d8e49bf67ff4aa97878dfaae866c6da516e12fa7d2bc2ba1e8d5973547";

#[test]
fn golden_rotate90_then_crop() {
    let src = noisy_frame(13, 29, 0xA5A5);
    let d = golden(
        "rotate90_crop",
        &src,
        vec![
            ("rotate", json!({"degrees": 90})),
            ("crop", json!({"x": 3, "y": 2, "width": 10, "height": 10})),
        ],
    );
    assert_eq!(d, GOLDEN_ROTATE90_CROP);
}

#[test]
fn golden_skewed_quad_rectification() {
    // A parallelogram "page" region inside a noisy frame.
    let src = noisy_frame(24, 24, 0x1234);
    let d = golden(
        "skew",
        &src,
        vec![(
            "perspective",
            json!({
                "corners": [[4.0, 1.0], [20.0, 4.0], [17.0, 21.0], [1.0, 18.0]],
                "width": 8,
                "height": 8
            }),
        )],
    );
    assert_eq!(d, GOLDEN_SKEW_RECTIFY);
}

#[test]
fn golden_shadow_flattening() {
    let src = shadow_frame(32, 32);
    let d = golden(
        "shadow",
        &src,
        vec![("illumination", json!({"mode": "flatten", "strength": 0.8}))],
    );
    assert_eq!(d, GOLDEN_SHADOW_FLATTEN);
}

#[test]
fn golden_chained_review_pipeline() {
    // The typical review flow: straighten, rectify the page quad, flatten.
    let src = shadow_frame(40, 40);
    let d = golden(
        "chain",
        &src,
        vec![
            ("rotate", json!({"degrees": 270})),
            (
                "perspective",
                json!({
                    "corners": [[3.0, 2.0], [34.0, 5.0], [31.0, 36.0], [2.0, 33.0]],
                    "width": 12,
                    "height": 12
                }),
            ),
            (
                "illumination",
                json!({"mode": "shadow_lift", "strength": 1.0}),
            ),
            ("crop", json!({"x": 1, "y": 1, "width": 10, "height": 10})),
        ],
    );
    assert_eq!(d, GOLDEN_CHAINED_PIPELINE);
}

#[test]
fn golden_balance_on_shadow() {
    let src = shadow_frame(24, 24);
    let d = golden(
        "balance",
        &src,
        vec![("illumination", json!({"mode": "balance"}))],
    );
    assert_eq!(d, GOLDEN_BALANCE_ON_SHADOW);
}

#[test]
fn golden_corruption_inputs_are_rejected_not_executed() {
    // Corrupted frame payload: rejected by bounds before any processing.
    let err = GrayFrame::from_pixels(4, 4, vec![1, 2, 3]).unwrap_err();
    assert_eq!(
        err.category,
        foldscan_domain::error::Category::InvalidRequest
    );

    // Truncated/oversize recipe documents remain rejected at the boundary.
    let err = ProcessingRecipe::from_json_bytes(b"{\"schema\":").unwrap_err();
    assert_eq!(
        err.category,
        foldscan_domain::error::Category::InvalidRequest
    );

    // A recipe referencing a degenerate quad is refused with no output.
    let src = noisy_frame(8, 8, 0x0F0F);
    let r = recipe_of(vec![(
        "perspective",
        json!({"corners": [[1.0, 1.0], [4.0, 4.0], [1.0, 4.0], [4.0, 1.0]], "width": 4, "height": 4}),
    )]);
    let err = apply_recipe(&src, &r).unwrap_err();
    assert_eq!(
        err.category,
        foldscan_domain::error::Category::InvalidRequest
    );
}

#[test]
fn golden_input_generators_are_stable() {
    // Guards the fixtures themselves: LCG streams are reproducible.
    assert_eq!(noisy_frame(13, 29, 0xA5A5), noisy_frame(13, 29, 0xA5A5));
    assert_ne!(noisy_frame(13, 29, 0xA5A5), noisy_frame(13, 29, 0xA5A6));
    assert_eq!(shadow_frame(32, 32), shadow_frame(32, 32));
}
