//! Cross-parser checks for the PDF export writer (issue #27).
//!
//! These tests consume the fixtures in `tests/fixtures/pdf/` that were
//! generated *by the crate's own writer* (via the `gen_pdf_fixture`
//! example) and validated at generation time with PyMuPDF — an independent
//! PDF parser — for page count, MediaBox pixel dimensions, and pixel-exact
//! image decoding (see `generate.py` and `manifest.json` beside the
//! fixtures). The manifest therefore carries third-parser evidence the
//! in-crate self-check cannot produce on its own: it proves the bytes our
//! writer claims are a valid image-page PDF are *read back* as exactly
//! those pages and pixels by a separate implementation.
//!
//! What is verified here at test time (from the committed manifest, without
//! re-running the generator):
//! - the fixture files on disk are exactly the files that were validated
//!   (SHA-256 pinned in the manifest),
//! - the crate's writer reproduces each fixture byte-for-byte from the
//!   documented (w, h, seed) page specs,
//! - the manifest's per-page digests equal recomputed `GrayFrame::digest()`
//!   values for the same synthetic frames — i.e. what PyMuPDF extracted at
//!   generation time was the *same pixel data* our frames encode.
//!
//! Evidence category: software fixture evidence (self-generated bytes,
//! independent-parser validation recorded at generation time). No device,
//! no optical bench, no print-output claim.

use foldscan_domain::{export_pdf, GrayFrame};
use serde_json::Value;

fn manifest() -> Value {
    let raw = include_str!("fixtures/pdf/manifest.json");
    serde_json::from_str(raw).expect("pdf fixture manifest parses")
}

struct Lcg(u16);

impl Lcg {
    fn next(&mut self) -> u8 {
        self.0 = self
            .0
            .wrapping_mul(25173)
            .wrapping_add(13849)
            .wrapping_shl(3)
            ^ self.0.wrapping_shr(5);
        (self.0 >> 8) as u8
    }
}

fn lcg_page(w: u32, h: u32, seed: u16) -> GrayFrame {
    let mut rng = Lcg(seed);
    let pixels = (0..(w * h)).map(|_| rng.next()).collect();
    GrayFrame::from_pixels(w, h, pixels).expect("fixture frame")
}

fn fixture(name: &str) -> Vec<u8> {
    match name {
        "one_page_5x4.pdf" => include_bytes!("fixtures/pdf/one_page_5x4.pdf").to_vec(),
        "three_pages.pdf" => include_bytes!("fixtures/pdf/three_pages.pdf").to_vec(),
        other => panic!("unmapped fixture {other}"),
    }
}

#[test]
fn committed_fixtures_match_manifest_digests() {
    let m = manifest();
    let fixtures = m["fixtures"].as_array().expect("fixtures array");
    assert!(!fixtures.is_empty());
    for entry in fixtures {
        let file = entry["file"].as_str().expect("file name");
        let want = entry["sha256"].as_str().expect("sha256");
        let got = foldscan_domain::checksum::sha256_hex(&fixture(file));
        assert_eq!(
            got, want,
            "fixture {file} drifted from generation-time bytes"
        );
    }
}

#[test]
fn writer_reproduces_each_fixture_byte_for_byte() {
    let m = manifest();
    for entry in m["fixtures"].as_array().expect("fixtures array") {
        let file = entry["file"].as_str().expect("file name");
        let pages: Vec<GrayFrame> = entry["pages"]
            .as_array()
            .expect("pages array")
            .iter()
            .map(|p| {
                lcg_page(
                    p["w"].as_u64().expect("w") as u32,
                    p["h"].as_u64().expect("h") as u32,
                    p["seed"].as_u64().expect("seed") as u16,
                )
            })
            .collect();
        let bytes = export_pdf(&pages).expect("writer output");
        assert_eq!(
            bytes,
            fixture(file),
            "writer output differs from committed fixture {file}"
        );
    }
}

#[test]
fn manifest_page_digests_match_grayframe_digests() {
    // The generator recorded, for every page PyMuPDF decoded from the
    // fixture, SHA-256 over the extracted pixels using the GrayFrame
    // recipe. Recompute the digest from the *source frame* the pixels were
    // generated from; equality closes the loop:
    // source frame -> writer -> PDF bytes -> PyMuPDF pixels -> same digest.
    let m = manifest();
    for entry in m["fixtures"].as_array().expect("fixtures array") {
        for p in entry["pages"].as_array().expect("pages array") {
            let w = p["w"].as_u64().expect("w") as u32;
            let h = p["h"].as_u64().expect("h") as u32;
            let seed = p["seed"].as_u64().expect("seed") as u16;
            let want = p["digest"].as_str().expect("digest");
            assert_eq!(
                lcg_page(w, h, seed).digest(),
                want,
                "PyMuPDF-extracted pixels for {w}x{h} seed {seed} differ from the source frame"
            );
        }
    }
}
